#!/bin/bash

if [ $# -ne 3 ]; then
  echo "Your command: $0 $*"
  echo "Usage: tidy4 <tidy dir> <src dir> <obj dir>"
  exit 1
else
  tidyDir="$1"
  srcDir="$2"
  objDir="$3"
fi

if [ -d "$tidyDir" ]; then
  echo "Tidying directory $tidyDir ..."
else
  echo "$tidyDir does not exist"
  exit 1
fi
if [ ! -d "$srcDir" ]; then
  if [ -f "$srcDir" ]; then
    echo "$srcDir exists and is not a directory"
    exit 1
  else
    mkdir "$srcDir"
  fi
fi
CFILES=$tidyDir/*.c*
if stat -t $CFILES >/dev/null 2>&1; then
  mv $CFILES $srcDir;
  echo "Moved C and C++ files to $srcDir"
fi
if [ ! -d "$objDir" ]; then
  if [ -f "$objDir" ]; then
    echo "$objDir exists and is not a directory"
    exit 1
  else
    mkdir "$objDir"
  fi
fi
OBJFILES=$tidyDir/*.o
if stat -t $OBJFILES >/dev/null 2>&1; then
  mv $OBJFILES $objDir
  echo "Moved object files to $objDir"
fi
echo "... done"

