#!/bin/bash
read -p "Type your name, please: " nm
echo Hello $nm.
echo The ultimate question of life, the universe, and everything...
read -p "Please Type the answer: " ch
while [ "$ch" != "42" ]
do
read -p "No, try again! " ch
done
echo That\’s right
